### PR TITLE
MetadataExtractor error improvements

### PR DESCRIPTION
**Pull request by wgoldie**
I have modified MetadataExtractor to include a parser library as discussed in #17. 

Instead of `jsonlint` I have included `json_parse.js` from https://github.com/douglascrockford/JSON-js in the vendor directory. 

`json_parse.js` emits errors with a structure that is better for our use case than that of `jsonlint` and it is public domain. 

The structure of the returned errors is the same as before, but with an additional `position` key for the position of the error on the line. The error message is slightly different, and follows the format

`Something is wrong with your ISF metadata: [parsing error from json_parse] at line X and position Y`

FYI, I built the library on Node 8 because submodule builds were failing on Node 10 and I didn't want to bump any versions - my `package.lock` will correspond to that environment. I'm not sure how you  handle those files and whether you browserify before commit, happy to make any changes necessary in that regard or others.

### CODE REVIEW

**Comment by msfeldstein** [comment]
This looks good.  have you linked it into the ISF Page app to verify it works as expected?

**Comment by msfeldstein** [comment]
i can npm publish it tomorrow if so

**Comment by wgoldie** [comment]
Yep, it's on the branch `new_isf_parser`. I'll merge that branch to staging once I can change the dependency from Github to the npm version.

**Comment by msfeldstein** [comment]
i just published v2.9.0

**Comment by wgoldie** [comment]
Thanks!

**Pull request merged**
